### ISSUE TITLE
gitignoreをReact用のものに置き換える

### ISSUE THREAD

**Issue by chore1110** [chore1110/react_app#1]
gitignoreが最低限のものしかないので修正する  
https://raw.github.com/github/gitignore/35c010258fc790ad769033e9ccfb1021178f2925/Node.gitignore  
上のリンクがひとまずは適当そうなので、そちらに置換

**Comment by Nissy1110** [comment]
https://qiita.com/Tsh-43879562/items/e2397035da33f910c5b5  
上のリンクにあるように、gitignoreを変更してpushしただけでは、すでにリポジトリにあるファイルは消えてくれない。
インデックス環境からファイルを消す必要がある

**Comment by chore1110** [comment]
マージされたのでClose
